2022-02-13 09:00:53 info: ---------------------------------------------
2022-02-13 09:00:53 info: >>> Running Unit Test `ex1-programmerFun` <<<
2022-02-13 09:00:53 info: ---------------------------------------------
2022-02-13 09:01:08 info: All unit tests passed.
2022-02-13 09:01:16 info: All steps were completed successfully
2022-02-14 06:48:34 info: ------------------------------------------
2022-02-14 06:48:34 info: >>> Running Unit Test `ex2-pokemonApp` <<<
2022-02-14 06:48:34 info: ------------------------------------------
2022-02-14 06:48:47 error: *** Unit Test Error Report ***

Command failed: npx jest ex2-pokemonApp.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex2-pokemonApp.test.js (6.843 s)
  pokemonApp
    ✕ HTML should be syntactically valid (187 ms)
    ✓ should have all TODO comments removed
    ✓ should use `fetch()`
    ✓ should use `await fetch()` (1 ms)
    ✓ should use try/catch

  ● pokemonApp › HTML should be syntactically valid

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "
    inline
      9:6  error  <form> element must have a submit button  wcag/h32·
    ✖ 1 problem (1 error, 0 warnings)
    "

      44 |   const { results } = htmlValidate.validateString(htmlText);
      45 |   const validationReport = stylish(results);
    > 46 |   expect(validationReport).toBe('');
         |                            ^
      47 | }
      48 |
      49 | module.exports = {

      at validateHTML (test-runner/jsdom-helpers.js:46:28)
      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex2-pokemonApp.test.js:40:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        7.124 s
Ran all test suites matching /ex2-pokemonApp.test.js/i.
2022-02-14 06:48:50 error: *** ESLint Report ***

ex2-pokemonApp/index.js
  63:11  warning  Please do not use `innerHTML` in the homework. Use `textContent` and/or `document.createElement()` instead  no-restricted-syntax

✖ 1 problem (0 errors, 1 warning)


2022-02-14 06:48:53 error: *** Spell Checker Report ***

ex2-pokemonApp/index.js:84:62 - Unknown word (Stas)

2022-02-14 07:29:45 info: ------------------------------------------
2022-02-14 07:29:45 info: >>> Running Unit Test `ex2-pokemonApp` <<<
2022-02-14 07:29:45 info: ------------------------------------------
2022-02-14 07:29:59 error: *** Unit Test Error Report ***

Command failed: npx jest ex2-pokemonApp.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex2-pokemonApp.test.js (6.889 s)
  pokemonApp
    ✕ HTML should be syntactically valid (187 ms)
    ✓ should have all TODO comments removed (1 ms)
    ✓ should use `fetch()`
    ✓ should use `await fetch()`
    ✓ should use try/catch (1 ms)

  ● pokemonApp › HTML should be syntactically valid

    expect(received).toBe(expected) // Object.is equality

    Expected: ""
    Received: "
    inline
      9:6  error  <form> element must have a submit button  wcag/h32·
    ✖ 1 problem (1 error, 0 warnings)
    "

      44 |   const { results } = htmlValidate.validateString(htmlText);
      45 |   const validationReport = stylish(results);
    > 46 |   expect(validationReport).toBe('');
         |                            ^
      47 | }
      48 |
      49 | module.exports = {

      at validateHTML (test-runner/jsdom-helpers.js:46:28)
      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex2-pokemonApp.test.js:40:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   0 total
Time:        7.151 s
Ran all test suites matching /ex2-pokemonApp.test.js/i.
2022-02-14 07:34:50 info: ------------------------------------------
2022-02-14 07:34:50 info: >>> Running Unit Test `ex2-pokemonApp` <<<
2022-02-14 07:34:50 info: ------------------------------------------
2022-02-14 07:35:02 info: All unit tests passed.
2022-02-14 07:35:08 info: All steps were completed successfully
2022-02-14 08:46:07 info: ----------------------------------------
2022-02-14 08:46:07 info: >>> Running Unit Test `ex4-diceRace` <<<
2022-02-14 08:46:07 info: ----------------------------------------
2022-02-14 08:46:07 info: Exercise has not yet been modified
2022-02-14 08:46:17 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-diceRace.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js
  ex4-diceRace
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (3 ms)
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✕ should use `dice.map()` (1 ms)
    ✕ should use `Promise.race()` (1 ms)
    ✕ should resolve as soon as a die settles successfully
    ✓ should reject with an Error as soon as a die rolls off the table (1 ms)

  ● ex4-diceRace › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex4-diceRace › should use `dice.map()`

    expect(received).toBeDefined()

    Received: undefined

      38 |
      39 |   test('should use `dice.map()`', () => {
    > 40 |     expect(state.diceMap).toBeDefined();
         |                           ^
      41 |   });
      42 |
      43 |   test('should use `Promise.race()`', () => {

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:40:27)

  ● ex4-diceRace › should use `Promise.race()`

    expect(received).toBeDefined()

    Received: undefined

      42 |
      43 |   test('should use `Promise.race()`', () => {
    > 44 |     expect(state.promiseAll).toBeDefined();
         |                              ^
      45 |   });
      46 |
      47 |   test('should resolve as soon as a die settles successfully', async () => {

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:44:30)

  ● ex4-diceRace › should resolve as soon as a die settles successfully

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      52 |
      53 |     const promise = rollDice();
    > 54 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      55 |     const result = await promise;
      56 |     expect(typeof result).toBe('string');
      57 |

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:54:21)

  ● ex4-diceRace › should resolve as soon as a die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      46 |
      47 |   test('should resolve as soon as a die settles successfully', async () => {
    > 48 |     expect.assertions(3);
         |            ^
      49 |     expect(exported).toBeDefined();
      50 |
      51 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:48:12)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 3 passed, 7 total
Snapshots:   0 total
Time:        1.532 s
Ran all test suites matching /ex4-diceRace.test.js/i.
2022-02-14 08:46:21 error: *** ESLint Report ***

ex4-diceRace.js
  14:7  error  'rollDie' is assigned a value but never used  no-unused-vars
  17:9  error  'dice' is assigned a value but never used     no-unused-vars

✖ 2 problems (2 errors, 0 warnings)


2022-02-14 08:46:39 info: -----------------------------------------
2022-02-14 08:46:39 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2022-02-14 08:46:39 info: -----------------------------------------
2022-02-14 08:46:45 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollAnAce.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js
  ex3-rollAnAce
    ✕ should have all TODO comments removed (3 ms)
    ✓ `rollDieUntil` should not contain unneeded console.log calls (1 ms)
    ✕ should not include a recursive call
    ✓ should use async/wait
    ✓ should use try/catch (1 ms)
    ✓ should resolve as soon as a die settles on an ACE (22 ms)
    ✓ should reject with an Error when a die rolls off the table (14 ms)

  ● ex3-rollAnAce › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex3-rollAnAce › should not include a recursive call

    expect(received).toBeUndefined()

    Received: true

      53 |
      54 |   test('should not include a recursive call', () => {
    > 55 |     expect(state.recursive).toBeUndefined();
         |                             ^
      56 |   });
      57 |
      58 |   test('should use async/wait', () => {

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js:55:29)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        1.251 s
Ran all test suites matching /ex3-rollAnAce.test.js/i.
2022-02-14 08:46:48 error: *** ESLint Report ***

ex3-rollAnAce.js
  27:11  error  'results' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-02-14 11:06:22 info: -----------------------------------------
2022-02-14 11:06:22 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2022-02-14 11:06:22 info: -----------------------------------------
2022-02-14 11:06:29 info: All unit tests passed.
2022-02-14 11:06:36 info: All steps were completed successfully
2022-02-14 11:07:05 info: -----------------------------------------
2022-02-14 11:07:05 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2022-02-14 11:07:05 info: -----------------------------------------
2022-02-14 11:07:10 info: All unit tests passed.
2022-02-14 11:07:15 info: All steps were completed successfully
2022-02-14 11:25:37 info: ----------------------------------------
2022-02-14 11:25:37 info: >>> Running Unit Test `ex4-diceRace` <<<
2022-02-14 11:25:37 info: ----------------------------------------
2022-02-14 11:25:47 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-diceRace.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js
  ex4-diceRace
    ✓ should exist and be executable (2 ms)
    ✓ should have all TODO comments removed (1 ms)
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✓ should use `dice.map()`
    ✓ should use `Promise.race()` (1 ms)
    ✕ should resolve as soon as a die settles successfully (3 ms)
    ✓ should reject with an Error as soon as a die rolls off the table (1 ms)

  ● ex4-diceRace › should resolve as soon as a die settles successfully

    expect(received).toBeInstanceOf(expected)

    Expected constructor: Promise

    Received value has no prototype
    Received value: undefined

      52 |
      53 |     const promise = rollDice();
    > 54 |     expect(promise).toBeInstanceOf(Promise);
         |                     ^
      55 |     const result = await promise;
      56 |     expect(typeof result).toBe('string');
      57 |

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:54:21)

  ● ex4-diceRace › should resolve as soon as a die settles successfully

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      46 |
      47 |   test('should resolve as soon as a die settles successfully', async () => {
    > 48 |     expect.assertions(3);
         |            ^
      49 |     expect(exported).toBeDefined();
      50 |
      51 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0);

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:48:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        1.322 s, estimated 2 s
Ran all test suites matching /ex4-diceRace.test.js/i.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Die 1 rolled off the table.
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
2022-02-14 11:28:04 info: ----------------------------------------
2022-02-14 11:28:04 info: >>> Running Unit Test `ex4-diceRace` <<<
2022-02-14 11:28:04 info: ----------------------------------------
2022-02-14 11:28:09 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-diceRace.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js
  ex4-diceRace
    ✓ should exist and be executable (2 ms)
    ✓ should have all TODO comments removed
    ✓ `rollDice` should not contain unneeded console.log calls (1 ms)
    ✓ should use `dice.map()` (1 ms)
    ✓ should use `Promise.race()`
    ✕ should resolve as soon as a die settles successfully (5 ms)
    ✕ should reject with an Error as soon as a die rolls off the table (1 ms)

  ● ex4-diceRace › should resolve as soon as a die settles successfully

    expect(received).toBe(expected) // Object.is equality

    Expected: "string"
    Received: "undefined"

      54 |     expect(promise).toBeInstanceOf(Promise);
      55 |     const result = await promise;
    > 56 |     expect(typeof result).toBe('string');
         |                           ^
      57 |
      58 |     promise.finally(() => {
      59 |       randomSpy.mockRestore();

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:56:27)

  ● ex4-diceRace › should reject with an Error as soon as a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      62 |
      63 |   test('should reject with an Error as soon as a die rolls off the table', async () => {
    > 64 |     expect.assertions(3);
         |            ^
      65 |     expect(exported).toBeDefined();
      66 |
      67 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex4-diceRace.test.js:64:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        1.289 s, estimated 2 s
Ran all test suites matching /ex4-diceRace.test.js/i.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Die 1 rolled off the table.
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
2022-02-14 11:35:21 info: ----------------------------------------
2022-02-14 11:35:21 info: >>> Running Unit Test `ex4-diceRace` <<<
2022-02-14 11:35:21 info: ----------------------------------------
2022-02-14 11:35:27 info: All unit tests passed.
2022-02-14 11:35:33 info: All steps were completed successfully
2022-02-15 01:16:49 info: ----------------------------------------
2022-02-15 01:16:49 info: >>> Running Unit Test `ex5-vscDebug` <<<
2022-02-15 01:16:49 info: ----------------------------------------
2022-02-15 01:16:49 warn: A unit test file was not provided.
2022-02-15 01:16:56 info: All steps were completed successfully
2022-02-15 01:17:14 info: --------------------------------------------
2022-02-15 01:17:14 info: >>> Running Unit Test `ex6-browserDebug` <<<
2022-02-15 01:17:14 info: --------------------------------------------
2022-02-15 01:17:14 warn: A unit test file was not provided.
2022-02-15 01:17:18 info: All steps were completed successfully
